# Generated by Django 3.1.1 on 2021-01-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descripcion',
            new_name='description',
        ),
    ]
