# Generated by Django 3.1.1 on 2021-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210113_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Introduccion'),
        ),
    ]
