# Generated by Django 3.1.1 on 2021-01-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='image',
            field=models.ImageField(upload_to='benefits_bg', verbose_name='Imagen'),
        ),
    ]
