# Generated by Django 3.1.1 on 2021-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_auto_20210115_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['order'], 'verbose_name': 'Beneficios', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.RemoveField(
            model_name='benefits',
            name='orderPriority',
        ),
        migrations.AddField(
            model_name='benefits',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
