# Generated by Django 3.1.1 on 2021-01-15 08:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0003_auto_20210115_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
