# Generated by Django 3.1.1 on 2021-01-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0004_auto_20210115_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'ordering': ['order'], 'verbose_name': 'Beneficios', 'verbose_name_plural': 'Beneficio'},
        ),
        migrations.AlterField(
            model_name='benefits',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
