# Generated by Django 3.1.1 on 2021-01-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['orderPriority'], 'verbose_name': 'Beneficios', 'verbose_name_plural': 'Beneficios'},
        ),
    ]
