# Generated by Django 3.1.1 on 2021-01-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210115_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['orderPriority'], 'verbose_name': 'Servicios', 'verbose_name_plural': 'Servicios'},
        ),
    ]
