# Generated by Django 3.1.1 on 2021-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210115_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
