# Generated by Django 3.1.1 on 2021-01-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='orderPriority',
            field=models.SmallIntegerField(unique=True, verbose_name='Orden'),
        ),
    ]
