# Generated by Django 3.1.1 on 2021-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210114_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['order'], 'verbose_name': 'Acerca De', 'verbose_name_plural': 'Acerca De'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='orderPriority',
        ),
        migrations.AddField(
            model_name='about',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
